# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deb298fbeb0d954da40bca1d8709c47722876874be5a2af02fe5b9efd67ef60c2105c90f042a816b4de6d5f591e566534da1158aaf87fb95fbe355fa1fd9ee89

test:
  secret_key_base: fcc7c8688d0ad8fc5d5492f3bc20e8af29ddda69f49ba777f2fa334f41ba2d731a4713a88225c23aeb889fb7ca8ee651742f227a09feb81aa268795c3427ad49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
